<?php return array (
  'site_title' => 'Bug Finder',
  'base_color' => 'ff5400',
  'time_zone' => 'UTC',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'deepblue',
  'fraction_number' => 0,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 0,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'push_notification' => 0,
  'error_log' => 0,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 0,
  'bonus_amount' => '20',
  'joining_bonus' => 1,
);